Repository cybsafe/phishtray, pull requests merged in 2018-10, with the labels that each got.

#102 99 add exit/finish button, fix postformdata error util
  frontend/src/components/Header/index.js
  frontend/src/utils.js
Labels: Needs Review

#100 add redux persist, clean up store, add initial Afterward page
  frontend/package.json
  frontend/src/App.js
  frontend/src/pages/Afterward/index.js
  frontend/src/redux.js
  frontend/yarn.lock
Labels: Needs Review

#106 update ui on afterward page, move clearing down store logic
  frontend/src/pages/Afterward/index.js
Labels: Needs Review

#105 101 participant actions for experiment start and stop
  frontend/src/App.js
  frontend/src/components/Header/index.js
  frontend/src/pages/Exercise/index.js
  frontend/src/pages/Inbox/components/Email.js
Labels: Needs Review

#111 Noticket stichup redux persist app clean up
  frontend/src/App.js
  frontend/src/pages/Afterward/index.js
  frontend/src/pages/Inbox/components/Email.js
  frontend/src/redux.js
  frontend/src/routes.js
Labels: Needs Review

#95 Improve email reveal time
  exercise/admin.py
  exercise/migrations/0003_auto_20181011_1656.py
  exercise/models.py
  exercise/serializer.py
  exercise/tests/test_models.py
  phishtray/settings.py
Labels: wip

#120 NOTICKET - quick fixup to avoid marking the same email received
  exercise/models.py
Labels: Ready

#119 118 - ExerciseFile
  exercise/admin.py
  exercise/factories.py
  exercise/migrations/0001_initial.py
  exercise/migrations/0002_auto_20180920_1148.py
  exercise/migrations/0003_auto_20181011_1656.py
  exercise/models.py
  exercise/serializer.py
  exercise/tests/test_api.py
  participant/migrations/0001_initial.py
  participant/models.py
  requirements.txt
Labels: Needs Review

#121 Multiple and code cleanup 109 117 114 116 113 115
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Button/ReplyButton.js
  frontend/src/components/Header/index.js
  frontend/src/components/WebBrowser/websites/Bluestar/assets/bg.png
  frontend/src/components/WebBrowser/websites/Bluestar/index.js
  frontend/src/components/WebBrowser/websites/MyOffice.js
  frontend/src/components/WebBrowser/websites/index.js
  frontend/src/pages/Afterward/index.js
  frontend/src/pages/Exercise/index.js
  frontend/src/pages/FileManager/components/FileListItem.js
  frontend/src/pages/FileManager/index.js
  frontend/src/pages/Inbox/components/Email.js
  frontend/src/pages/Web/index.js
  frontend/src/reducers/fileManagerReducer.js
  frontend/src/routes.js
  frontend/src/utils.js
Labels: Needs Review

#127 126 add contacts page
  frontend/src/data/contacts.js
  frontend/src/pages/Contacts/components/ContactDetail.js
  frontend/src/pages/Contacts/components/ContactListItem.js
  frontend/src/pages/Contacts/index.js
  frontend/src/routes.js
  frontend/src/utils.js
Labels: Needs Review

#130 Cleanup action log add actions
  frontend/src/actions/uiActions.js
  frontend/src/components/Header/index.js
  frontend/src/components/WebBrowser/WebBrowser.js
  frontend/src/components/WebBrowser/websites/Bluestar/index.js
  frontend/src/components/WebBrowser/websites/MyPayment/index.js
  frontend/src/config/actionTypes.js
  frontend/src/pages/Accounts/index.js
  frontend/src/pages/Contacts/index.js
  frontend/src/pages/Exercise/index.js
  frontend/src/pages/FileManager/index.js
  frontend/src/pages/Inbox/components/Email.js
  frontend/src/pages/Inbox/components/EmailListItem.js
  frontend/src/pages/Inbox/components/QuickReply.js
  frontend/src/reducers/uiReducer.js
  frontend/src/utils.js
Labels: Needs Review

#134 GH-125 - CSV serializer for Participant ActionLogs, exercise-reports …
  exercise/serializer.py
  exercise/views.py
  participant/serializer.py
  phishtray/api_urls.py
  phishtray/base.py
Labels: Needs Review

#136 add static debrief page
  frontend/src/pages/Afterward/index.js
Labels: wip

#143 NOTICKET - email is only a thread if it belongs_to itself
  exercise/views.py
Labels: Needs Review

#148 Gh 125/participant report csv download
  exercise/serializer.py
  exercise/views.py
  participant/serializer.py
Labels: Needs Review

#151 NOTICKET - fix logic in thread endpoint tests
  exercise/tests/test_api.py
Labels: Needs Review

#155 Noticket/makefile improvements
  Makefile
  exercise/migrations/0004_auto_20181017_1035.py
Labels: Needs Review, enhancement
