Repository cybsafe/phishtray, pull requests merged in 2019-11, with the labels that each got.

#322 Feature/308 warning web page
  frontend/src/components/ActionLink/ActionLinkwithClick.js
  frontend/src/components/WebBrowser/websites/Warning/index.js
  frontend/src/components/WebBrowser/websites/index.js
  frontend/src/pages/Inbox/components/Email.js
  frontend/src/pages/Web/index.js
  frontend/src/utils.js
Labels: frontend

#328 Feature/242 participant nested filtering
  exercise/helpers.py
  exercise/models.py
  exercise/queryset.py
  exercise/tests/test_helpers.py
  participant/admin.py
  participant/filters.py
Labels: backend

#327 NOTICKET: extended Organization Scope
  exercise/admin.py
  exercise/managers.py
  exercise/migrations/0018_auto_20191104_1647.py
  exercise/models.py
  exercise/queryset.py
  participant/admin.py
Labels: Ready, backend

#341 339 - cache busting & email properties sync
  exercise/apps.py
  exercise/models.py
  exercise/signals.py
  phishtray/base.py
  phishtray/settings.py
  utils/cache.py
Labels: backend

#337 188 - Number Field Required
  frontend/src/pages/Exercise/index.js
Labels: Needs Review

#343 340 removed image upload fields from exercise
  exercise/migrations/0019_auto_20191107_1613.py
  exercise/models.py
Labels: backend

#350 347: Organization scoped Emails, DRYed earlier scoped ones
  exercise/admin.py
  exercise/managers.py
  exercise/migrations/0020_auto_20191108_1355.py
  exercise/models.py
  exercise/queryset.py
  participant/managers.py
  participant/models.py
  participant/queryset.py
  phishtray/base.py
Labels: Needs Review, backend

#385 384 - strat to delete items on .delete() and purge soft deleted records
  exercise/migrations/0021_purge_softdeleted_items.py
  participant/migrations/0004_auto_20191115_1121.py
  participant/models.py
  phishtray/base.py
  phishtray/test/tests.py
Labels: backend

#388 384-remove-softdelete-phase-II
  exercise/admin.py
  exercise/helpers.py
  exercise/migrations/0021_auto_20191115_1728.py
  exercise/migrations/0021_purge_softdeleted_items.py
  exercise/models.py
  exercise/queryset.py
  exercise/templatetags/exercise_admin_extras.py
  exercise/tests/test_helpers.py
  exercise/tests/test_models.py
  exercise/tests/test_querysets.py
  exercise/views.py
  participant/migrations/0005_auto_20191115_1728.py
  participant/tests/test_querysets.py
  phishtray/base.py
  phishtray/test/tests.py
  users/models.py
Labels: Needs Review, backend

#391 369: Multitenancy for Demographics
  exercise/admin.py
  exercise/migrations/0022_demographicsinfo_organization.py
  exercise/models.py
Labels: backend

#395 370: Multitenancy for ExerciseTask & EmailReplyTaskScore
  exercise/admin.py
  exercise/migrations/0023_auto_20191119_1530.py
  exercise/models.py
Labels: Ready, backend

#374 Feature/241 trial stats csv
  participant/admin.py
  participant/helpers.py
Labels: Needs Review, backend

#404 Multitenancy Users
  docker/local/Makefile
  docker/local/hooks/pre-commit
  local.Dockerfile
  participant/managers.py
  participant/models.py
  participant/queryset.py
  phishtray/base.py
  requirements-dev.txt
  users/admin.py
  users/managers.py
  users/migrations/0004_auto_20191119_1628.py
  users/models.py
  users/tests/test_querysets.py
Labels: backend

#399 371: added Multitenancy to Organization Admin
  participant/admin.py
Labels: backend

#405 Change default training link
  frontend/src/pages/TrainingPage/index.js
Labels: Ready, frontend

#411 HOTFIX - sync email props
  exercise/models.py
Labels: backend

#409 406: added Multitenancy to Exercise Admin
  exercise/admin.py
Labels: Ready, backend

#413 407: Extended EmailDebrief with action_id
  participant/models.py
  participant/tests/test_api.py
Labels: backend

#410 Use useSelector and useDispatch
  frontend/src/pages/Inbox/components/QuickReply.js
Labels: frontend

#398 Techdebt/364 inbox
  frontend/src/pages/Inbox/components/EmailListItem.js
  frontend/src/pages/Inbox/index.js
Labels: Needs Review, frontend

#412 refactor Emailchain to react hooks and redux hooks
  frontend/src/pages/Inbox/components/EmailChain.js
Labels: frontend

#419 418: added exercise.queryset tests
  exercise/tests/test_querysets.py
  users/queryset.py
Labels: Needs Review, backend

#386 Techdebt/362 update exercise
  frontend/src/pages/Exercise/index.js
Labels: frontend

#421 Adding new actions to the user stats csv
  participant/helpers.py
Labels: Ready, backend

#387 Techdebt/363 update filemanager index
  frontend/src/pages/FileManager/index.js
  frontend/src/pages/Inbox/components/Email.js
Labels: Needs Review, frontend
