Repository cybsafe/phishtray, pull requests merged in 2019-10, with the labels that each got.

#238 fix migration issues after introducing custom user model
  docker/local/Makefile
  local.Dockerfile
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20190930_1718.py
  users/migrations/0002_user_organization.py
Labels: Ready

#249 244 exercise help text
  exercise/migrations/0007_auto_20191003_0946.py
  exercise/models.py
Labels: Ready

#252 add option to fake 0002 migration for users as those tables will like…
  docker/local/Makefile
Labels: Needs Review

#255 GH-221 Participant Behaviour & Actions
  exercise/models.py
  participant/constants.py
  participant/models.py
Labels: Needs Review

#259 add config to enable coveralls
  .coveragerc
  .travis.yml
  README.md
  docker/local/Makefile
  requirements.txt
Labels: Needs Review

#261 tidy up users app and exclude a few more files from coverage
  .coveragerc
  users/forms.py
  users/tests.py
  users/tests/__init__.py
  users/views.py
Labels: Needs Review

#256 added phishing email reactions list
  participant/serializer.py
  participant/tests/test_api.py
Labels: backend

#272 268: added OrganizationQueryset tests
  participant/factories.py
  participant/queryset.py
  participant/tests/test_querysets.py
  users/factories.py
Labels: Ready, backend

#274 269: added tests for Participant Queryset
  participant/queryset.py
  participant/tests/test_querysets.py
Labels: Needs Review, backend

#279 278: Upcycled ExerciseWebPages
  exercise/admin.py
  exercise/migrations/0008_auto_20191010_1359.py
  exercise/models.py
  exercise/tests/test_models.py
Labels: Ready

#286 282 remove exercise url
  exercise/admin.py
  exercise/migrations/0009_delete_exerciseurl.py
  exercise/models.py
Labels: backend

#287 281 block exercise
  exercise/factories.py
  exercise/migrations/0010_auto_20191011_1501.py
  exercise/models.py
  exercise/tests/test_models.py
Labels: Ready

#273 Feature/240 copy exercise
  exercise/admin.py
  exercise/helpers.py
  exercise/migrations/0011_exercise_copied_from.py
  exercise/models.py
  exercise/templatetags/__init__.py
  exercise/templatetags/exercise_admin_extras.py
  exercise/tests/test_helpers.py
  phishtray/settings.py
  templates/admin/exercise/change_form.html
  templates/admin/exercise/exercise_submit_line.html
Labels: Needs Review, backend

#300 297: moved phishing_explained to participant-scores endpoint
  exercise/serializer.py
  participant/serializer.py
Labels: backend

#293 289 exercise email properties serializers
  exercise/models.py
  exercise/serializer.py
  exercise/tests/test_api.py
  exercise/tests/test_models.py
Labels: backend

#310 307:added filter and search to ExerciseEmailProperties
  exercise/admin.py
Labels: Ready, backend

#316 added handling and tests for UserQuerySet
  users/queryset.py
  users/tests/test_querysets.py
Labels: Ready, backend

#318 Feature/251 exercise trial
  exercise/admin.py
  exercise/helpers.py
  exercise/migrations/0014_auto_20191024_1522.py
  exercise/models.py
  exercise/queryset.py
  exercise/templatetags/exercise_admin_extras.py
  templates/admin/exercise/exercise_submit_line.html
Labels: Ready, backend, enhancement

#319 317: added received_date to ExerciseEmailProperties
  exercise/migrations/0015_exerciseemailproperties_date_received.py
  exercise/models.py
  exercise/serializer.py
  exercise/tests/test_api.py
  exercise/tests/test_models.py
Labels: Ready, backend

#321 Testing helper methods
  exercise/helpers.py
  exercise/migrations/0016_auto_20191025_1624.py
  exercise/models.py
  exercise/tests/test_helpers.py
  exercise/tests/test_models.py
Labels: Needs Review, backend

#324 Exercise Init
  exercise/helpers.py
  exercise/migrations/0017_auto_20191028_1730.py
  exercise/models.py
  exercise/tests/test_helpers.py
  exercise/tests/test_models.py
  exercise/views.py
Labels: backend

#320 Feature/263 blocked web page
  frontend/src/components/ActionLink/ActionLinkwithClick.js
  frontend/src/components/Header/index.js
  frontend/src/components/InlineNotification/index.js
  frontend/src/components/WebBrowser/WebBrowser.js
  frontend/src/components/WebBrowser/websites/Blocked/index.js
  frontend/src/components/WebBrowser/websites/Blocked/ui/index.js
  frontend/src/components/WebBrowser/websites/index.js
  frontend/src/pages/Debrief/index.js
  frontend/src/pages/Inbox/components/Email.js
  frontend/src/pages/Inbox/components/QuickReply.js
  frontend/src/pages/Web/index.js
  frontend/src/utils.js
Labels: frontend
